// Example 1: Disable one check

[tool.djangodoctor]
//disable = ["redundant-settings"]
//disable = ["redundant-settings", "missing-hsts-subdomain"]
//disable = ["all"]
enable = ["redundant-settings", "missing-hsts-subdomain"]
